<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Trabalhando o banco de dados – Análise de sobrevivência aplicado a dados epidemiológicos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-2fef5ea3f8957b3e4ecc936fc74692ca.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c27fdc8e5b00b532d2d5a75ada188648.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-b9e11ad5a37ead2aabff839d95ae3857.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-c27fdc8e5b00b532d2d5a75ada188648.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./intro.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Trabalhando o banco de dados</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Análise de sobrevivência aplicado a dados epidemiológicos</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Sobre o banco de dados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Trabalhando o banco de dados</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Sumário</h2>
   
  <ul>
  <li><a href="#dinâmica-das-doenças-sg-vs.-srag" id="toc-dinâmica-das-doenças-sg-vs.-srag" class="nav-link active" data-scroll-target="#dinâmica-das-doenças-sg-vs.-srag"><span class="header-section-number">2.1</span> Dinâmica das doenças SG vs.&nbsp;SRAG</a>
  <ul class="collapse">
  <li><a href="#tempo-até-a-cura-comportamento-entre-gêneros-e-classificação-de-casos" id="toc-tempo-até-a-cura-comportamento-entre-gêneros-e-classificação-de-casos" class="nav-link" data-scroll-target="#tempo-até-a-cura-comportamento-entre-gêneros-e-classificação-de-casos"><span class="header-section-number">2.1.1</span> Tempo até a cura: comportamento entre gêneros e classificação de casos</a></li>
  <li><a href="#tempo-até-o-óbito-comportamento-entre-gêneros-e-classificação-de-casos" id="toc-tempo-até-o-óbito-comportamento-entre-gêneros-e-classificação-de-casos" class="nav-link" data-scroll-target="#tempo-até-o-óbito-comportamento-entre-gêneros-e-classificação-de-casos"><span class="header-section-number">2.1.2</span> Tempo até o óbito: comportamento entre gêneros e classificação de casos</a></li>
  <li><a href="#tempo-até-oóbito-por-outras-causas-comportamento-entre-gêneros-e-classificação-de-casos" id="toc-tempo-até-oóbito-por-outras-causas-comportamento-entre-gêneros-e-classificação-de-casos" class="nav-link" data-scroll-target="#tempo-até-oóbito-por-outras-causas-comportamento-entre-gêneros-e-classificação-de-casos"><span class="header-section-number">2.1.3</span> Tempo até oóbito por outras causas: comportamento entre gêneros e classificação de casos</a></li>
  <li><a href="#hipótese-testadas-para-o-estimador-kaplan-meier-pela-teste-logrank." id="toc-hipótese-testadas-para-o-estimador-kaplan-meier-pela-teste-logrank." class="nav-link" data-scroll-target="#hipótese-testadas-para-o-estimador-kaplan-meier-pela-teste-logrank."><span class="header-section-number">2.1.4</span> Hipótese testadas para o estimador Kaplan-Meier pela teste Logrank.</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Trabalhando o banco de dados</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>O banco de dados ‘esus.sivep.covid19bh’ do ano de 2023 possui um total de 132.804 observações e 11 variáveis. No entanto as colunas que teram enfoque são apenas 6 - sexo, racacor, dt_sin_pri, forma_doenca, classificacao e evolucao.</p>
<p>Após filtrar foi identificado apenas uma observação como ‘na’ sendo descartada, o total de observações passa a ser de 132.803.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       sexo           racacor dt_sin_pri forma_doenca classificacao
1  Feminino Sem preenchimento 2023-02-15           SG     Suspeitos
2  Feminino            Branca 2023-03-08           SG     Suspeitos
3 Masculino            Branca 2023-01-01           SG   Confirmados
         evolucao
1 Em investigação
2 Em investigação
3 Em investigação</code></pre>
</div>
</div>
<p>Para trabalha com o tempo para uma análise de sobrevivência é necessário identificar a variável em que se tem informação sobre os sintomas das formas da doença, principalmente em relação ao início de ocorrência. Pela natureza das datas, não é possível a priori, trabalhar o tempo desta maneira, mas é possível transformar para uma forma em que seja estimado os tempos de sobrevivência. Com o pacote ‘lubridate’ se pode captar numericamente os dias e agrupar o número de ocorrência de sintomas primários nos 12 meses.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>tempo
    1     2     3     4     5     6     7     8     9    10    11    12 
14605 13605 15874 13320 16275 11533  8386  5848  6466  8644 11834  6413 </code></pre>
</div>
</div>
<p>Para o status, baseado na natureza e organização dos dados trabalhar com a variável ‘evolucao’ se torna um desafio entender, a princípio para identificar e estimar as falhas como evento de interesse. Por isso, eu criei 3 tipos de status, tomando como falhas: cura, óbito e óbito por outras causas. Os casos tidos como ‘Em investigação’ e ‘Em monitoramento’, seram tratados como censura, uma vez que o paciente não apresentou os eventos de interesse apresentados.</p>
<p>Há também a variável ‘classificacao’, sendo interessante para identificar a quantidade de casos confirmados e estimar as falhas de interesse, bem como identificar os casos suspeitos e descartados para quantificar e entender quantos desses foram apresentaram os eventos de interesse e se existe conflito entre os eventos de ‘óbito’ e ‘óbitos por outras causas’.</p>
<p>Assim o banco de dados estudado fica com 9 variáveis para serem trabalhadas.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       sexo           racacor dt_sin_pri forma_doenca classificacao
1  Feminino Sem preenchimento 2023-02-15           SG     Suspeitos
2  Feminino            Branca 2023-03-08           SG     Suspeitos
3 Masculino            Branca 2023-01-01           SG   Confirmados
         evolucao status_1 status_2 status_3
1 Em investigação        0        0        0
2 Em investigação        0        0        0
3 Em investigação        0        0        0</code></pre>
</div>
</div>
<section id="dinâmica-das-doenças-sg-vs.-srag" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="dinâmica-das-doenças-sg-vs.-srag"><span class="header-section-number">2.1</span> Dinâmica das doenças SG vs.&nbsp;SRAG</h2>
<p>O que queremos investigar: os tempo de vida de pacientes notificados com suspeita de Síndrome Gripal - SG e Sindrome Respiratória Agúda Grave - SRAG.</p>
<p>Temos algumas linhas de investigação:</p>
<ul>
<li><p>Entender pela cura;</p></li>
<li><p>Entender pelos óbitos;</p></li>
<li><p>Entender quantos desses casos foram confirmados.</p></li>
<li><p>Quantos desses casos foram descartados.</p></li>
</ul>
<p>Segundo as informações do próprio repositório, o SG é por covid19.</p>
<section id="tempo-até-a-cura-comportamento-entre-gêneros-e-classificação-de-casos" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="tempo-até-a-cura-comportamento-entre-gêneros-e-classificação-de-casos"><span class="header-section-number">2.1.1</span> Tempo até a cura: comportamento entre gêneros e classificação de casos</h3>
<p>Pela tabela gerada pelo pacote ‘survival’ do R, se pode percerbe que existe uma estabilidade na probabilidade de sobrevivência principalmente no grupo de pessoas com a forma da doença Síndrome Gripal. Quer dizer que há mais demora até um paciente ser curado. No entanto, apesar de haver muitas notificações de casos de Síndrome Gripal, existe poucos eventos em que esses paciente de fato se curaram.</p>
<p>Para os casos de paciente com Síndrome Respiratória Agúda Grave, houve consideráveis observações de pessoas que se curaram da doença, com probabilidades de não sobrevivência de praticamente 73% no 12 mês do ano de 2023, indicando que apesar das notificações, os pacientes conseguiram se curar.</p>
<p>Em ambos os grupos, podemos observar que houve muitas notificações, onde ao passar dos meses essa notificações foram oscilando e diminuindo drasticamente, principalmente no grupo de pessoas com SRAG. Isto indica que houve censuras, seja por óbitos devido as doenças, óbitos por outro fatores ou mesmo pela perda de acompanhamento desses paciente.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(tempo, status_1) ~ forma_doenca, data = df_fit)

                forma_doenca=SG 
 time n.risk n.event survival  std.err lower 95% CI upper 95% CI
    1 125340      63    0.999 6.33e-05        0.999        1.000
    2 111532      57    0.999 9.26e-05        0.999        0.999
    3  98755      39    0.999 1.12e-04        0.998        0.999
    4  83688      20    0.998 1.24e-04        0.998        0.999
    5  71018      28    0.998 1.45e-04        0.998        0.998
    6  55498      16    0.998 1.61e-04        0.997        0.998
    7  44641       8    0.997 1.73e-04        0.997        0.998
    8  36895      11    0.997 1.95e-04        0.997        0.998
    9  31539      37    0.996 2.74e-04        0.995        0.997
   10  25529      35    0.995 3.58e-04        0.994        0.995
   11  17353      33    0.993 4.85e-04        0.992        0.994
   12   6051      21    0.989 8.93e-04        0.988        0.991

                forma_doenca=SRAG 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
    1   7463      93    0.988 0.00128        0.985        0.990
    2   6666      58    0.979 0.00170        0.976        0.982
    3   5838      51    0.970 0.00206        0.966        0.974
    4   5031      39    0.963 0.00237        0.958        0.968
    5   4381      56    0.951 0.00286        0.945        0.956
    6   3626      39    0.940 0.00326        0.934        0.947
    7   2950      24    0.933 0.00359        0.926        0.940
    8   2310      27    0.922 0.00411        0.914        0.930
    9   1818      47    0.898 0.00528        0.888        0.908
   10   1362      64    0.856 0.00720        0.842        0.870
   11    894      86    0.773 0.01065        0.753        0.795
   12    362      22    0.726 0.01395        0.700        0.754</code></pre>
</div>
</div>
<p>Gráficamente podemos observa melhor a curva de Kaplan-Meier:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(tempo, status_1) ~ classificacao, data = df_fit)

                classificacao=Confirmados 
 time n.risk n.event survival  std.err lower 95% CI upper 95% CI
    1  12061     124    0.990 0.000919        0.988        0.992
    2  10818      74    0.983 0.001203        0.981        0.985
    3  10404      60    0.977 0.001401        0.975        0.980
    4   9567      43    0.973 0.001547        0.970        0.976
    5   8665      62    0.966 0.001770        0.962        0.969
    6   7527      42    0.961 0.001946        0.957        0.964
    7   7142      25    0.957 0.002052        0.953        0.961
    8   6857      30    0.953 0.002181        0.949        0.957
    9   6381      67    0.943 0.002477        0.938        0.948
   10   5132      81    0.928 0.002939        0.922        0.934
   11   2750      99    0.895 0.004347        0.886        0.903
   12    744      29    0.860 0.007600        0.845        0.875

                classificacao=Descartados 
 time n.risk n.event survival  std.err lower 95% CI upper 95% CI
    1  32795      32    0.999 0.000172        0.999        0.999
    2  30170      41    0.998 0.000273        0.997        0.998
    3  27301      28    0.997 0.000334        0.996        0.997
    4  23437      16    0.996 0.000375        0.995        0.997
    5  19370      22    0.995 0.000445        0.994        0.996
    6  15052      13    0.994 0.000505        0.993        0.995
    7  11597       7    0.993 0.000553        0.992        0.994
    8   9518       8    0.993 0.000626        0.991        0.994
    9   8021      16    0.991 0.000797        0.989        0.992
   10   6160      18    0.988 0.001047        0.986        0.990
   11   3903      20    0.983 0.001536        0.980        0.986
   12   1468      14    0.973 0.002920        0.968        0.979

                classificacao=Suspeitos 
 time n.risk n.event survival  std.err lower 95% CI upper 95% CI
    3  66888       2        1 2.11e-05            1            1
    9  18955       1        1 5.68e-05            1            1</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="tempo-até-o-óbito-comportamento-entre-gêneros-e-classificação-de-casos" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="tempo-até-o-óbito-comportamento-entre-gêneros-e-classificação-de-casos"><span class="header-section-number">2.1.2</span> Tempo até o óbito: comportamento entre gêneros e classificação de casos</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(tempo, status_2) ~ forma_doenca, data = df_fit)

                forma_doenca=SG 
     time n.risk n.event survival std.err lower 95% CI upper 95% CI

                forma_doenca=SRAG 
 time n.risk n.event survival  std.err lower 95% CI upper 95% CI
    1   7463      20    0.997 0.000598        0.996        0.998
    2   6666       8    0.996 0.000732        0.995        0.998
    3   5838      11    0.994 0.000924        0.992        0.996
    4   5031      12    0.992 0.001148        0.990        0.994
    5   4381      17    0.988 0.001475        0.985        0.991
    6   3626       6    0.986 0.001616        0.983        0.990
    7   2950       9    0.983 0.001897        0.980        0.987
    8   2310       3    0.982 0.002033        0.978        0.986
    9   1818      10    0.977 0.002644        0.972        0.982
   10   1362      22    0.961 0.004230        0.953        0.969
   11    894      29    0.930 0.007012        0.916        0.944
   12    362      12    0.899 0.011068        0.878        0.921</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(tempo, status_2) ~ classificacao, data = df_fit)

                classificacao=Confirmados 
 time n.risk n.event survival  std.err lower 95% CI upper 95% CI
    1  12061      20    0.998 0.000370        0.998        0.999
    2  10818       8    0.998 0.000453        0.997        0.998
    3  10404      11    0.997 0.000553        0.995        0.998
    4   9567      12    0.995 0.000660        0.994        0.997
    5   8665      17    0.993 0.000811        0.992        0.995
    6   7527       6    0.993 0.000872        0.991        0.994
    7   7142       9    0.991 0.000966        0.989        0.993
    8   6857       3    0.991 0.000997        0.989        0.993
    9   6381      10    0.989 0.001110        0.987        0.991
   10   5132      22    0.985 0.001427        0.982        0.988
   11   2750      29    0.975 0.002382        0.970        0.979
   12    744      12    0.959 0.005075        0.949        0.969

                classificacao=Descartados 
     time n.risk n.event survival std.err lower 95% CI upper 95% CI

                classificacao=Suspeitos 
     time n.risk n.event survival std.err lower 95% CI upper 95% CI</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="tempo-até-oóbito-por-outras-causas-comportamento-entre-gêneros-e-classificação-de-casos" class="level3" data-number="2.1.3">
<h3 data-number="2.1.3" class="anchored" data-anchor-id="tempo-até-oóbito-por-outras-causas-comportamento-entre-gêneros-e-classificação-de-casos"><span class="header-section-number">2.1.3</span> Tempo até oóbito por outras causas: comportamento entre gêneros e classificação de casos</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(tempo, status_3) ~ forma_doenca, data = df_fit)

                forma_doenca=SG 
     time n.risk n.event survival std.err lower 95% CI upper 95% CI

                forma_doenca=SRAG 
 time n.risk n.event survival std.err lower 95% CI upper 95% CI
    1   7463     682   0.9086 0.00334       0.9021       0.9152
    2   6666     758   0.8053 0.00461       0.7963       0.8144
    3   5838     745   0.7025 0.00534       0.6921       0.7131
    4   5031     598   0.6190 0.00569       0.6080       0.6303
    5   4381     675   0.5236 0.00588       0.5122       0.5353
    6   3626     623   0.4337 0.00587       0.4223       0.4453
    7   2950     587   0.3474 0.00568       0.3364       0.3587
    8   2310     441   0.2811 0.00540       0.2707       0.2919
    9   1818     374   0.2232 0.00505       0.2136       0.2334
   10   1362     352   0.1655 0.00459       0.1568       0.1748
   11    894     365   0.0980 0.00384       0.0907       0.1058
   12    362     290   0.0195 0.00219       0.0156       0.0243</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-18-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Call: survfit(formula = Surv(tempo, status_3) ~ classificacao, data = df_fit)

                classificacao=Confirmados 
     time n.risk n.event survival std.err lower 95% CI upper 95% CI

                classificacao=Descartados 
 time n.risk n.event survival  std.err lower 95% CI upper 95% CI
    1  32795     682    0.979 0.000788        0.978        0.981
    2  30170     758    0.955 0.001170        0.952        0.957
    3  27301     745    0.929 0.001477        0.926        0.931
    4  23437     598    0.905 0.001728        0.901        0.908
    5  19370     675    0.873 0.002050        0.869        0.877
    6  15052     623    0.837 0.002423        0.832        0.842
    7  11597     587    0.795 0.002863        0.789        0.800
    8   9518     441    0.758 0.003223        0.752        0.764
    9   8021     374    0.723 0.003553        0.716        0.730
   10   6160     352    0.681 0.003974        0.674        0.689
   11   3903     365    0.618 0.004802        0.608        0.627
   12   1468     290    0.496 0.007486        0.481        0.511

                classificacao=Suspeitos 
     time n.risk n.event survival std.err lower 95% CI upper 95% CI</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="intro_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="hipótese-testadas-para-o-estimador-kaplan-meier-pela-teste-logrank." class="level3" data-number="2.1.4">
<h3 data-number="2.1.4" class="anchored" data-anchor-id="hipótese-testadas-para-o-estimador-kaplan-meier-pela-teste-logrank."><span class="header-section-number">2.1.4</span> Hipótese testadas para o estimador Kaplan-Meier pela teste Logrank.</h3>
<section id="hipótese-p-cura" class="level4" data-number="2.1.4.1">
<h4 data-number="2.1.4.1" class="anchored" data-anchor-id="hipótese-p-cura"><span class="header-section-number">2.1.4.1</span> Hipótese p/ cura</h4>
<p><strong>SG vs SRAG</strong></p>
<p><span class="math inline">\(H_{0}\)</span>: A probabilidade de cura é igual entre os pacientes com Síndrome Gripal (SG) e Síndrome Respiratória Aguda Grave (SRAG) ao longo de 1 ano de acompanhamento.</p>
<p><span class="math inline">\(H_{1}\)</span>: A probabilidade de cura é diferente em pelo menos um dos pacientes com Síndrome Gripal (SG) e Síndrome Respiratória Aguda Grave (SRAG) em algum ponto de tempo ao longo de 1 ano de acompanhamento.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = Surv(tempo, status_1) ~ forma_doenca, data = df_fit, 
    rho = 0)

                       N Observed Expected (O-E)^2/E (O-E)^2/V
forma_doenca=SG   125340      368    920.1       331      5995
forma_doenca=SRAG   7463      606     53.9      5649      5995

 Chisq= 5995  on 1 degrees of freedom, p= &lt;2e-16 </code></pre>
</div>
</div>
<p>Conclusão: p &lt; 0.05, logo se rejeita <span class="math inline">\(H_{0}\)</span>, portanto a probabilidade de cura é diferente em pelo menos um dos paciente com SG e SRAG em algum ponto de tempo ao longo de 1 ano de acompanhamente.</p>
<p>Se nota que houve altas expectativa para notificações de pessoas curadas da Síndrome Gripal, mas ocorreu o oposto: de 921 esperadas, apenas 388 se curaram. Enquanto que se esperava 54 pessoas curadas da Síndrome Respiratória Agúda Grave, 606 se curaram da SRAG.</p>
<p><strong>Classificados: confirmados, suspeito e descartados</strong></p>
<p><span class="math inline">\(H_{0}\)</span>: A probabilidade de cura é igual entre os pacientes classificados como casos (confirmados, suspeito e descartados) ao longo de 1 ano de acompanhamento.</p>
<p><span class="math inline">\(H_{1}\)</span>: A probabilidade de cura é diferente em pelo menos um dos pacientes classificados como casos (confirmados, suspeitos e descartados) em algum ponto de tempo ao longo de 1 ano de acompanhamento.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = Surv(tempo, status_1) ~ classificacao, data = df_fit, 
    rho = 0)

                              N Observed Expected (O-E)^2/E (O-E)^2/V
classificacao=Confirmados 12061      736      126  2.95e+03  3.44e+03
classificacao=Descartados 32795      235      238  3.14e-02  4.17e-02
classificacao=Suspeitos   87947        3      610  6.04e+02  1.63e+03

 Chisq= 3610  on 2 degrees of freedom, p= &lt;2e-16 </code></pre>
</div>
</div>
<p>Conclusão: p &lt; 0.05, logo se rejeita <span class="math inline">\(H_{0}\)</span>, portanto a probabilidade de cura é diferente em pelo menos um dos pacientes classificados como casos (confirmados, suspeito e descartados) em algum ponto de tempo ao longo de 1 ano de acompanhamente.</p>
<p>Podemos observar que que entre os grupos classificados dos casos, era esperado 126 casos confirmados, 238 descartados e 610 suspeitos. O que se observou foi que houve mais de 50% de casos confirmados, enquantos que houve casos descartados que atingiram praticamamente a expectativa com erro para menos 3 observações e dos casos esperados como suspeitos eram extremamente altos, na realidade não passaram de 5 casos.</p>
</section>
<section id="hipótese-p-óbito-devido-uma-das-doenças" class="level4" data-number="2.1.4.2">
<h4 data-number="2.1.4.2" class="anchored" data-anchor-id="hipótese-p-óbito-devido-uma-das-doenças"><span class="header-section-number">2.1.4.2</span> Hipótese p/ óbito devido uma das doenças</h4>
<p><strong>SG vs SRAG</strong></p>
<p><span class="math inline">\(H_{0}\)</span>: A probabilidade de óbito é igual entre os pacientes com Síndrome Gripal (SG) e Síndrome Respiratória Aguda Grave (SRAG) ao longo de 1 ano de acompanhamento.</p>
<p><span class="math inline">\(H_{1}\)</span>: A probabilidade de óbito é diferente em pelo menos um dos pacientes com Síndrome Gripal (SG) e Síndrome Respiratória Aguda Grave (SRAG) em algum ponto de tempo ao longo de 1 ano de acompanhamento.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = Surv(tempo, status_2) ~ forma_doenca, data = df_fit, 
    rho = 0)

                       N Observed Expected (O-E)^2/E (O-E)^2/V
forma_doenca=SG   125340        0   150.28       150      2743
forma_doenca=SRAG   7463      159     8.72      2591      2743

 Chisq= 2744  on 1 degrees of freedom, p= &lt;2e-16 </code></pre>
</div>
</div>
<p>Conclusão: p &lt; 0.05, logo se rejeita <span class="math inline">\(H_{0}\)</span>, portanto a probabilidade de óbito é diferente em pelo menos um dos pacientes com Síndrome Gripal (SG) e Síndrome Respiratória Aguda Grave (SRAG) em algum ponto de tempo ao longo de 1 ano de acompanhamente.</p>
<p>Pelo teste, era esperado um número de 151 pessoas que viriam a óbito pela SG, o observado foi que dos 125.340 casos observados, nenhuma pessoa veio a óbito. Por outro lado era esperado que apenas 9 pessoas viriam a morrer de vido ao SRAG, se observou que esse valor cresceu mais que o dobro do esperado, sendo quase 160 pessoas.</p>
<p><strong>Classificados: confirmados, suspeito e descartados</strong></p>
<p><span class="math inline">\(H_{0}\)</span>: A probabilidade de óbito é igual entre os pacientes classificados como casos (confirmados, suspeito e descartados) ao longo de 1 ano de acompanhamento.</p>
<p><span class="math inline">\(H_{1}\)</span>: A probabilidade de óbito é diferente em pelo menos um dos pacientes classificados como casos (confirmados, suspeito e descartados) em algum ponto de tempo ao longo de 1 ano de acompanhamento.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = Surv(tempo, status_2) ~ classificacao, data = df_fit, 
    rho = 0)

                              N Observed Expected (O-E)^2/E (O-E)^2/V
classificacao=Confirmados 12061      159     21.4     884.5    1034.1
classificacao=Descartados 32795        0     38.2      38.2      50.4
classificacao=Suspeitos   87947        0     99.4      99.4     266.1

 Chisq= 1034  on 2 degrees of freedom, p= &lt;2e-16 </code></pre>
</div>
</div>
<p>Conclusão: p &lt; 0.05, logo se rejeita <span class="math inline">\(H_{0}\)</span>, portanto a probabilidade de óbito é diferente em pelo menos um dos pacientes classificados como casos (confirmados, suspeito e descartados) em algum ponto de tempo ao longo de 1 ano de acompanhamente.</p>
<p>Surpreendentemente os casos confirmados são exatamente os casos por SRAG, onde não se observou nenhum caso considerado suspeito, tão pouco descartadado. Era esperado quase 40 e 100 observações de ambos. Isto evidencia que não parece existe dependencia entre mortes devido a SRAG ou mortes por outro motivos desses pacientes, indicando a letalidade da doênça.</p>
</section>
<section id="hipótese-p-óbito-por-outras-causas" class="level4" data-number="2.1.4.3">
<h4 data-number="2.1.4.3" class="anchored" data-anchor-id="hipótese-p-óbito-por-outras-causas"><span class="header-section-number">2.1.4.3</span> Hipótese p/ óbito por outras causas</h4>
<p><strong>SG vs SRAG</strong></p>
<p><span class="math inline">\(H_{0}\)</span>: A probabilidade de óbito por outras causas é igual entre os pacientes com Síndrome Gripal (SG) e Síndrome Respiratória Aguda Grave (SRAG) ao longo de 1 ano de acompanhamento.</p>
<p><span class="math inline">\(H_{1}\)</span>: A probabilidade de óbito por outras causas é diferente em pelo menos um dos pacientes com Síndrome Gripal (SG) e Síndrome Respiratória Aguda Grave (SRAG) em algum ponto de tempo ao longo de 1 ano de acompanhamento.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = Surv(tempo, status_3) ~ forma_doenca, data = df_fit, 
    rho = 0)

                       N Observed Expected (O-E)^2/E (O-E)^2/V
forma_doenca=SG   125340        0     6121      6121    108924
forma_doenca=SRAG   7463     6490      369    101588    108924

 Chisq= 108925  on 1 degrees of freedom, p= &lt;2e-16 </code></pre>
</div>
</div>
<p>Conclusão: p &lt; 0.05, logo se rejeita <span class="math inline">\(H_{0}\)</span>, portanto a probabilidade de óbito por outras causas é diferente em pelo menos um dos pacientes com Síndrome Gripal (SG) e Síndrome Respiratória Aguda Grave (SRAG) em algum ponto de tempo ao longo de 1 ano de acompanhamente.</p>
<p>Um indicador interessante que mostra o quanto era esperado dos casos de cada doença é perceber que se esperaça mais de 6 mil casos de pacientes que viriam a óbito pela SG contra 370 da SRAG. O que ocorreu foi parecido com o teste para os óbitos: nenhuma observação para esse grupo e um grande volume de pessoas que morreram devido a outras causas.</p>
<p><strong>Classificados: confirmados, suspeito e descartados</strong></p>
<p><span class="math inline">\(H_{0}\)</span>: A probabilidade de óbito por outras causas é igual entre os pacientes classificados como casos (confirmados, suspeito e descartados) ao longo de 1 ano de acompanhamento.</p>
<p><span class="math inline">\(H_{1}\)</span>: A probabilidade de óbito por outras causas é diferente em pelo menos um dos pacientes classificados como casos (confirmados, suspeito e descartados) em algum ponto de tempo ao longo de 1 ano de acompanhamento.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Call:
survdiff(formula = Surv(tempo, status_3) ~ classificacao, data = df_fit, 
    rho = 0)

                              N Observed Expected (O-E)^2/E (O-E)^2/V
classificacao=Confirmados 12061        0      819       819       958
classificacao=Descartados 32795     6490     1611     14769     19881
classificacao=Suspeitos   87947        0     4059      4059     10994

 Chisq= 19881  on 2 degrees of freedom, p= &lt;2e-16 </code></pre>
</div>
</div>
<p>Conclusão: p &lt; 0.05, logo se rejeita <span class="math inline">\(H_{0}\)</span>, portanto a probabilidade de óbito por outras causas é diferente em pelo menos um dos pacientes classificados como casos (confirmados, suspeito e descartados) em algum ponto de tempo ao longo de 1 ano de acompanhamente.</p>
<p>Se confirma agora pelo teste Logrank que a curva de Kaplan-Meier indicou: todos os dados observados que foram tidos como mortes por outras causas são todos os casos que foram descartados.</p>
<p>Se pode concluir que o</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link" aria-label="Sobre o banco de dados">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Sobre o banco de dados</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>